server:
  port: 8083

spring:
  application:
    name: stocks
  config:
    import:
      - aws-secretsmanager:/secret/stocks/
      - aws-parameterstore:/config/stocks/
      - aws-parameterstore:/config/application/
  rsocket:
    server:
      mapping-path: "/rsocket"
      transport: "websocket"


management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true


logging:
  level:
    #        org.springframework.security: TRACE
    #        root: DEBUG
    org.springframework.data: DEBUG
    io.r2dbc: DEBUG
