#server:
#  port: 0
server:
  port: 8083


spring:
  application:
    name: stocks
  config:
    import:
      - aws-secretsmanager:/secret/stocks/
      - aws-parameterstore:/config/stocks/
      - aws-parameterstore:/config/application/

eureka:
  client:
    service-url:
      defaultZone: ${eureka.default.zone}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}


logging:
  level:
    #        org.springframework.security: TRACE
    #        root: DEBUG
    org.springframework.data: DEBUG
    io.r2dbc: DEBUG
