#server:
#  port: 0
server:
  port: 8083


spring:
  application:
    name: stocks

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

api:
  polygon:
    secret: Bearer ${POLYGON_API_KEY}
    base-url: https://api.polygon.io


    #logging:
    #  level:
    #    org.springframework.security: TRACE
#    root: DEBUG