server:
  port: 8083

market-data:
  fetch-cron: 0 00 17 * * MON-FRI
  delete-duplicates-cron: 0 30 17 * * MON-FRI


spring:
  application:
    name: stocks
  config:
    import:
      - aws-secretsmanager:/secret/stocks/
      - aws-parameterstore:/config/stocks/
      - aws-parameterstore:/config/application/
  rsocket:
    server:
      mapping-path: "/rsocket"
      transport: "websocket"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.base-url}/realms/${keycloak.realm}
  flyway:
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: ${spring.jdbc.url}


management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true


logging:
  level:
    #        org.springframework.security: TRACE
    #    root: DEBUG
    org.springframework.data: TRACE
    io.r2dbc: TRACE
